package com.iitd.app.service;

import com.iitd.app.entity.Submission;
import com.iitd.app.entity.User;
import com.iitd.app.repository.SubmissionRepository;
import com.iitd.app.repository.UserRepository;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.*;
import java.util.UUID;

@Service
public class SubmissionService {

    @Autowired
    private SubmissionRepository submissionRepository;

    @Autowired
    private UserRepository userRepository;

    @Value("${file.upload-dir}")
    private String uploadDir;

    public Submission saveSubmission(String email, String fullName, String submissionEmail,
            String mobileNumber, MultipartFile pdfFile) throws IOException {
        if (pdfFile == null || pdfFile.isEmpty()) {
            throw new IllegalArgumentException("PDF file is required");
        }
        String contentType = pdfFile.getContentType();
        if (contentType == null || !contentType.equals("application/pdf")) {
            throw new IllegalArgumentException("Only PDF files are allowed");
        }

        Path uploadPath = Paths.get(uploadDir);
        if (!Files.exists(uploadPath)) {
            Files.createDirectories(uploadPath);
        }

        String uniqueFilename = UUID.randomUUID() + "_" + pdfFile.getOriginalFilename();
        Path filePath = uploadPath.resolve(uniqueFilename);
        Files.copy(pdfFile.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);

        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Submission submission = new Submission();
        submission.setUser(user);
        submission.setFullName(fullName);
        submission.setEmail(submissionEmail);
        submission.setMobileNumber(mobileNumber);
        submission.setPdfPath(filePath.toString());

        return submissionRepository.save(submission);
    }

    public byte[] generateUserPdf(String userEmail) throws IOException {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Submission submission = submissionRepository
                .findTopByUserIdOrderBySubmittedAtDesc(user.getId())
                .orElseThrow(() -> new RuntimeException("No submission found for user"));

        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                float margin = 60;
                float pageWidth = page.getMediaBox().getWidth();
                float pageHeight = page.getMediaBox().getHeight();
                float yStart = pageHeight - margin;

                contentStream.setNonStrokingColor(0.07f, 0.09f, 0.18f);
                contentStream.addRect(0, pageHeight - 110, pageWidth, 110);
                contentStream.fill();

                contentStream.setNonStrokingColor(1f, 1f, 1f);
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 26);
                contentStream.newLineAtOffset(margin, pageHeight - 65);
                contentStream.showText("User Data Report");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 11);
                contentStream.setNonStrokingColor(0.7f, 0.78f, 1f);
                contentStream.newLineAtOffset(margin, pageHeight - 90);
                contentStream.showText("Generated by IITD User Data Collection Portal");
                contentStream.endText();

                contentStream.setStrokingColor(0.39f, 0.51f, 1f);
                contentStream.setLineWidth(3);
                contentStream.moveTo(margin, yStart - 120);
                contentStream.lineTo(pageWidth - margin, yStart - 120);
                contentStream.stroke();

                float y = yStart - 145;
                contentStream.setNonStrokingColor(0.39f, 0.51f, 1f);
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 13);
                contentStream.newLineAtOffset(margin, y);
                contentStream.showText("PERSONAL DETAILS");
                contentStream.endText();

                y -= 25;
                String[][] fields = {
                        { "Full Name", submission.getFullName() },
                        { "Email Address", submission.getEmail() },
                        { "Mobile Number", submission.getMobileNumber() },
                        { "PDF File Path", submission.getPdfPath() }
                };

                for (String[] field : fields) {
                    contentStream.setNonStrokingColor(0.45f, 0.45f, 0.55f);
                    contentStream.beginText();
                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 10);
                    contentStream.newLineAtOffset(margin, y);
                    contentStream.showText(field[0].toUpperCase());
                    contentStream.endText();

                    y -= 16;

                    contentStream.setNonStrokingColor(0.1f, 0.1f, 0.2f);
                    contentStream.beginText();
                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                    contentStream.newLineAtOffset(margin, y);
                    String value = field[1] != null ? field[1] : "N/A";
                    if (value.length() > 80)
                        value = value.substring(0, 77) + "...";
                    contentStream.showText(value);
                    contentStream.endText();

                    y -= 30;
                }

            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            document.save(baos);
            return baos.toByteArray();
        }
    }
}
